import { Trade } from "./trade-types";

export const mockTrades: Trade[] = [
  {
    id: "t1",
    symbol: "SPY",
    market: "Stocks",
    timeframe: "15m",
    direction: "LONG",
    entry: 502.4,
    stop: 501.1,
    tp1: 504.2,
    tp2: 506.0,
    entryZoneLow: 502.1,
    entryZoneHigh: 502.55,
    tooLateIfAbove: 503.1,
    status: "READY",
    confidence: "A",
    reasons: [
      { label: "ORB bias bullish", detail: "Above ORB high after first 30m" },
      { label: "VWAP hold", detail: "Retest held VWAP with higher lows" },
      { label: "VP reclaim", detail: "Reclaimed prior day POC" },
    ],
    entryRules: [
      { title: "Enter on retest", description: "Price tags entry zone and holds for 1 candle." },
      { title: "Momentum confirm", description: "Close above trigger candle high." },
    ],
    invalidationRules: [
      { title: "Stop hit", description: "Exit immediately if price trades at/through stop." },
      { title: "Structure break", description: "Exit if lower low prints below retest swing." },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    symbol: "BTC",
    market: "Crypto",
    timeframe: "15m",
    direction: "SHORT",
    entry: 68950,
    stop: 69480,
    tp1: 68150,
    tp2: 67300,
    entryZoneLow: 68880,
    entryZoneHigh: 69040,
    tooLateIfBelow: 68600,
    status: "WAITING",
    confidence: "A-",
    reasons: [
      { label: "Liquidity sweep fail", detail: "Sweep above range high then reversal" },
      { label: "HTF bearish", detail: "4H downtrend; rallies are sells" },
      { label: "VP rejection", detail: "Rejected LVN into supply" },
    ],
    entryRules: [{ title: "Wait for zone touch", description: "No entry unless price returns to entry zone." }],
    invalidationRules: [{ title: "Stop hit", description: "Exit immediately at stop." }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t3",
    symbol: "SOL",
    market: "Crypto",
    timeframe: "15m",
    direction: "LONG",
    entry: 178.2,
    stop: 175.9,
    tp1: 185.0,
    status: "ACTIVE",
    confidence: "A+",
    reasons: [
      { label: "Break-retest-reclaim", detail: "Reclaimed key level with retest hold" },
      { label: "Trend aligned", detail: "4H uptrend; continuation setup" },
    ],
    entryRules: [{ title: "Trigger", description: "Enter on close above reclaim level." }],
    invalidationRules: [{ title: "Stop hit", description: "Exit immediately." }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t4",
    symbol: "QQQ",
    market: "Stocks",
    timeframe: "15m",
    direction: "SHORT",
    entry: 446.8,
    stop: 448.1,
    tp1: 443.5,
    tp2: 441.2,
    status: "INVALIDATED",
    confidence: "B+",
    reasons: [
      { label: "Failed reclaim", detail: "Could not reclaim range high" },
      { label: "ORB bias down", detail: "ORB break and retest failed" },
    ],
    entryRules: [{ title: "Enter on rejection", description: "Wick into level + bearish close." }],
    invalidationRules: [{ title: "Stop hit", description: "Exit immediately." }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t5",
    symbol: "AAPL",
    market: "Stocks",
    timeframe: "15m",
    direction: "LONG",
    entry: 193.6,
    stop: 192.4,
    tp1: 196.2,
    status: "WAITING",
    confidence: "B",
    reasons: [
      { label: "Support hold", detail: "Held prior day VAL" },
      { label: "VWAP reclaim", detail: "Reclaimed VWAP after dip" },
    ],
    entryRules: [{ title: "Zone touch", description: "Enter only inside entry zone." }],
    invalidationRules: [{ title: "Stop hit", description: "Exit immediately." }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t6",
    symbol: "ETH",
    market: "Crypto",
    timeframe: "15m",
    direction: "SHORT",
    entry: 3520,
    stop: 3575,
    tp1: 3425,
    status: "READY",
    confidence: "A",
    reasons: [
      { label: "VP rejection at POC", detail: "Rejected POC after bounce" },
      { label: "Lower highs", detail: "Bearish structure intact" },
    ],
    entryRules: [{ title: "Enter in zone", description: "Enter when price is within entry tolerance." }],
    invalidationRules: [{ title: "Stop hit", description: "Exit immediately." }],
    updatedAt: new Date().toISOString(),
  },
];
